baseURL = "https://stuffbymax.me/cv-hugo/"
languageCode = "en-gb"
title = "Martin Petik - CV"
theme = "hugo-resume"
sectionPagesMenu = "main"
pagination.pagerSize = 10

[params]
  mainSections = ["post"]
